
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Dell
 */
public class StartingFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartingFrame
     */
    public StartingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openCustomerPortalBtn = new javax.swing.JButton();
        openAdminPortalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        openCustomerPortalBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        openCustomerPortalBtn.setText("Open Customer Portal");
        openCustomerPortalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCustomerPortalBtnActionPerformed(evt);
            }
        });

        openAdminPortalBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        openAdminPortalBtn.setText("Open Admin Portal");
        openAdminPortalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAdminPortalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(openCustomerPortalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openAdminPortalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openCustomerPortalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openAdminPortalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openCustomerPortalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCustomerPortalBtnActionPerformed
        // TODO add your handling code here:
        this.setTitle("Opening Customer Portal, PLease await.....");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        CustomerPortalFrame customerPortalFrame = new CustomerPortalFrame();
        customerPortalFrame.setSize(screenSize);
        customerPortalFrame.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_openCustomerPortalBtnActionPerformed

    private void openAdminPortalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAdminPortalBtnActionPerformed
        // TODO add your handling code here:
        this.setTitle("Opening Admin Portal, PLease await.....");
        String url = "http://alfredosrainelle.com/wp-admin/admin.php?page=energyplus";
        AdminPortalFrame adminPortalFrame = new AdminPortalFrame();
        adminPortalFrame.openPage(url);
        adminPortalFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openAdminPortalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
        try {
            FlatLightLaf.setup();
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }else{
                    javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                    StartingFrame startFrame = new StartingFrame();
//                    startFrame.setLocation(screenSize/2);
                    startFrame.setVisible(true);
                    
                }
            });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton openAdminPortalBtn;
    private javax.swing.JButton openCustomerPortalBtn;
    // End of variables declaration//GEN-END:variables
}
